version: 0.0
os: linux
files:
  - source: /revision.txt
    destination: /home/ubuntu/testcodedeploy
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 300
      runas: ubuntu
